apiVersion: v1
kind: ConfigMap
metadata:
  name: managed-upgrade-operator-config
data:
  config.yaml: |
    maintenance:
      controlPlaneTime: 90
      ignoredAlerts:
        controlPlaneCriticals:
        - etcdMembersDown
        - KubeDeploymentReplicasMismatch
        - ClusterOperatorDown
        - MachineWithNoRunningPhase
        - ClusterOperatorDegraded
    scale:
      timeOut: 30
    upgradeWindow:
      timeOut: 60
    nodeDrain:
      timeOut: 45
      workerNodeTime: 8
    healthCheck:
      ignoredCriticals:
      - DNSErrors05MinSRE
      - MetricsClientSendFailingSRE
      - UpgradeNodeScalingFailedSRE
      - UpgradeClusterCheckFailedSRE
