apiVersion: v1
kind: ConfigMap
metadata:
  name: osd-upgrade-config
data:
  config.yaml: |
    maintenance:
      controlPlaneTime: 90
      workerNodeTime: 8
    scale:
      timeOut: 30
    upgradeWindow:
      timeOut: 60
    nodeDrain:
      timeOut: 45